version: '3'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: front-tallosflix
    ports:
      - 8080:8080
    tty: true
    restart: always
    networks:
      - tallosflix
    volumes:
      - .:/user/app-front/app

networks:
  tallosflix: